# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbhack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='wfi_at_buy',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
